spring:
  application:
    name: default  # Dùng cho mọi service nếu không có file riêng

  profiles:
    active: dev

  cloud:
    discovery:
      enabled: true

  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

# Kafka config (chung cho các service nếu cần)
# kafka:
#   bootstrap-servers: localhost:9092

# Các thông số timeout có thể dùng chung
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
